using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Darkmatter.Presentation
{
    public class DeathScreenView : MonoBehaviour
    {

        [SerializeField] private GameObject deathScreen;
        public Button restartBtn;
        public Button exitBtn;
        public Button leaderBoardBtn;
        public TextMeshProUGUI score;
        public TextMeshProUGUI highScore;

        public void Show(int _score, int _highScore)
        {
            this.score.text = _score.ToString();
            this.highScore.text = _highScore.ToString();
            deathScreen.SetActive(true);
        }
        public void Hide()
        {
            deathScreen.SetActive(false);
        }
    }
}
