using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Darkmatter.Presentation
{
    public class GameScreenView : MonoBehaviour
    {
        [SerializeField] private GameObject gameScreen;
        public Button pauseBtn;
        [SerializeField] private TextMeshProUGUI scoreText;

        public void UpdateScore(int score)
        {
            scoreText.text = score.ToString();
        }

        public void Show()
        {
            gameScreen.SetActive(true);
        }

        public void Hide()
        {
            gameScreen.SetActive(false);
        }
    }
}
