using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class DeathScreenView : MonoBehaviour
{
    public GameObject deathScreen;
    public Button rePlayButton;
    public Button backButton;
    public TextMeshProUGUI highScoreText;
    public TextMeshProUGUI currentScoreText;
    private void Start()
    {
        deathScreen.SetActive(false);
    }

    public void Show(int score, int highscore)
    {
        highScoreText.text = highscore.ToString();
        currentScoreText.text = score.ToString();
        deathScreen.SetActive(true);

    }
    public void Hide()
    {
        deathScreen.SetActive(false);
    }
}
