using Darkmatter.Core;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Darkmatter.Presentation
{
    public class LeaderBoardData : MonoBehaviour,ILeaderBoardData
    {
        public Image BackgroundPanel;
        public TextMeshProUGUI playerPos;
        public TextMeshProUGUI playerName;
        public TextMeshProUGUI playerScore;

        public void ResetData()
        {
            BackgroundPanel.color = Color.white;
            playerPos.text = string.Empty;
            playerName.text = string.Empty;
            playerScore.text = string.Empty;
        }
    }
}
