using Darkmatter.Domain;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Darkmatter.Presentation
{
    public class LeaderBoardView : MonoBehaviour
    {
        public GameObject leaderBoardScreen;
        public Button ExitButton;
        public LeaderBoardData LBplayerData;
        public TextMeshProUGUI loadingText;

        public void Show()
        {
            leaderBoardScreen.SetActive(true); 
        }

        public void Hide()
        {
            leaderBoardScreen.SetActive(false);
        }

        public void ShowLoading(bool shouldShow)
        {
            loadingText.gameObject.SetActive(shouldShow);
        }
    }
}
